### ISSUE TITLE
FSDP example doesn't work on P5 instance.

### ISSUE THREAD

**Issue by aruncs2005** [aws-samples/awsome-distributed-training#103]
When running the FSDP example on P5 instance we get the below error. 
CUDA Capability sm_90 for H100 GPUs required.

We need to update the pytorch version to 2.1 or above to fix the issue

**Comment by KeitaW** [comment]
Thanks for reporting! Which specific use case causing the issue?

**Comment by sean-smith** [comment]
Fixed in https://github.com/aws-samples/awsome-distributed-training/pull/104
