### ISSUE TITLE
SMHP: easy_ssh.bin does not work from Cloudshell

### ISSUE THREAD

**Issue by verdimrc** [aws-samples/awsome-distributed-training#129]
Does not work Cloudshell, but works from a workstation.

![cloudshell-easy-ssh](https://github.com/aws-samples/awsome-distributed-training/assets/2340781/cfe259df-5db2-44d3-ba13-20478304d475)

**Comment by sean-smith** [comment]
Try setting the region explicitly.

**Comment by verdimrc** [comment]
Resolved. There was a missing permission.
