### ISSUE TITLE
Remove git dependency

### ISSUE THREAD

**Issue by sean-smith** [aws-samples/awsome-distributed-training#134]
https://github.com/aws-samples/awsome-distributed-training/blob/d66304ff17229dd857397d725ed9e168bc41167f/1.architectures/5.sagemaker-hyperpod/LifecycleScripts/base-config/utils/install_enroot_pyxis.sh#L47

**Comment by sean-smith** [comment]
This should be:


```bash
PYXIS_VERSION="v0.17.0"
wget https://github.com/NVIDIA/pyxis/archive/refs/tags/${PYXIS_VERSION}.zip
```

**Comment by verdimrc** [comment]
0.18.0 just out.
