### ISSUE TITLE
Add guidance on new UCX for new NGC containers

### ISSUE THREAD

**Issue by perifaws** [aws-samples/awsome-distributed-training#16]
From @verdimrc 

> When basing on latest NVidia pytorch container FROM [nvcr.io/nvidia/pytorch:23.09-py3](http://nvcr.io/nvidia/pytorch:23.09-py3), make sure not to remove the hpcx stuffs (and the ld.conf file) -- except for the hpcx's mpi. 
> 
> Because it seems Nvidia build the latest pytorch to always look for the hpcx libraries. If you remove hpcx (incl. the ld.conf file), then import torch will complain about missing libuc?.so.*.

**Comment by sean-smith** [comment]
Yes we've seen this in our docker images and no longer remove these. Let's update https://github.com/aws-samples/awsome-distributed-training/blob/main/3.test_cases/1.megatron-lm/2.distributed-training.Dockerfile#L19

**Comment by verdimrc** [comment]
Closed.
