### ISSUE TITLE
Add disable GSP firmware

### ISSUE THREAD

**Issue by mhuguesaws** [aws-samples/awsome-distributed-training#17]
Before installing the NVIDIA driver
```bash
echo "options nvidia NVreg_EnableGpuFirmware=0" | sudo tee -a /etc/modprobe.d/nvidia-gsp.conf
```

You can check the status of GSP by
```bash
cat /proc/driver/nvidia/params | grep EnableGpuFirmware
```

It should return a `EnableGpuFirmware: 0` to indicate GSP is disabled:
```bash
EnableGpuFirmware: 0
EnableGpuFirmwareLogs: 2
```

**Comment by sean-smith** [comment]
1. Edit the file `/etc/modprobe.d/nvidia-gsp.conf` and set the flag:
```bash
options nvidia NVreg_EnableGpuFirmware=0
```
2. Then reboot with `sudo reboot`
3. Create the AMI
