### ISSUE TITLE
Add time sync checks across all nodes to verify nodes aren't drifting apart.

### ISSUE THREAD

**Issue by DarkSector** [aws-samples/awsome-distributed-training#180]
In rare cases, PyTorch will timeout due to drift in system clock across nodes. A pre-check may be useful to diagnose this issue before training run starts. 

Add test to hyperpod-precheck.py

**Comment by sean-smith** [comment]
We can run the command:

```bash
srun -N 16 bash -c 'echo "$(hostname): $(date)"' | sort -k2,3
```

And somehow programmatically make sure the dates are within 1 sec or each other.
