### ISSUE TITLE
Create quick-create deployment for Cloudformation scripts

### ISSUE THREAD

**Issue by perifaws** [aws-samples/awsome-distributed-training#21]
Feature to add 1 click deployments for the CloudFormation scripts for the VPC, Batch and S3.

https://github.com/aws-samples/awsome-distributed-training/tree/main/1.architectures

Quick create reference:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-console-create-stacks-quick-create-links.html

**Comment by SurajpratapsinghSayar** [comment]
Hi @perifaws, 

Good Day!
I see the quick-create link has not been created for aws-batch yet. Could you assign this to me?

Thanks,
Suraj

**Comment by perifaws** [comment]
Hey @SurajpratapsinghSayar , done for this issue. Let me know if you prefer an issue specific to Batch. Thanks!

**Comment by SurajpratapsinghSayar** [comment]
@perifaws sure I would like to work on it. Also, I will need some guidance. Thanks!!
