### ISSUE TITLE
Change from Dockerhub to Public ECR

### ISSUE THREAD

**Issue by sean-smith** [aws-samples/awsome-distributed-training#335]
The following line can cause rate limits from Dockerhub:

https://github.com/aws-samples/awsome-distributed-training/blob/1d15afd847f7810125c60353a09a1757188ba7aa/1.architectures/5.sagemaker-hyperpod/LifecycleScripts/base-config/utils/install_efa_node_exporter.sh#L19

We should switch this image to pull from [Public ECR](https://gallery.ecr.aws/).

**Comment by mhuguesaws** [comment]
```
public.ecr.aws/docker/library/ubuntu:20.04
```
