### ISSUE TITLE
PlacementGroup option for "Capacity Blocks for ML" 

### ISSUE THREAD

**Issue by liyier90** [aws-samples/awsome-distributed-training#353]
In the pcluster config (https://github.com/aws-samples/awsome-distributed-training/blob/main/1.architectures/2.aws-parallelcluster/distributed-training-p4de-base.yaml#L42-L43), there is a comment saying we should set `PlacementGroup` to `Enabled: false` when using a targeted ODCR.

May I know if this applies for a targeted "Capacity Blocks for ML"?

**Comment by liyier90** [comment]
Thanks for the explanation @sean-smith . May I know if there is a distinction between ODCR and Capacity Block because Capacity Block is listed as a different reservation type on the console.

![chrome_5rpCWJUicS](https://github.com/aws-samples/awsome-distributed-training/assets/56420072/1195a3f9-9e8b-4c03-98c5-022bceea9cb8)

**Comment by mhuguesaws** [comment]
Capacity block is time based ODCR with instances placed by default in a placement group cluster.

**Comment by mhuguesaws** [comment]
Closing
