### ISSUE TITLE
Bump Megatron LM example from 0.4 to 0.8.0 (or latest as option)

### ISSUE THREAD

**Issue by perifaws** [aws-samples/awsome-distributed-training#370]
The [MegatronLM](https://github.com/aws-samples/awsome-distributed-training/tree/main/3.test_cases/1.megatron-lm) sample is set to 0.4 and needs an update to a later version starting at 0.7. The version should be configurable with a default in the docker file (top). 

This is the part to update but there will be dependencies changes, for example on transformers and NCCL + OFI.

```
RUN cd /workspace && git clone --depth 1 --branch core_v0.4.0 https://github.com/NVIDIA/Megatron-LM.git \
	&& cd Megatron-LM \
	&& python3 -m pip install nltk  \
	&& python -m pip install .
```

**Comment by mhuguesaws** [comment]
This requires actions due to 1y+ packages.
