### ISSUE TITLE
problem following the workshop

### ISSUE THREAD

**Issue by superwhu919** [aws-samples/awsome-distributed-training#410]
i was following the workship provided in the first page of this repo. https://catalog.workshops.aws/sagemaker-hyperpod/en-US
In the step 1.b., setup lifecycle scripts, after run the bash file,
`bash create_config.sh`
i get the error below:

```[INFO]` AWS_REGION = us-east-2
[WARNING] INSTANCES environment variable is not set, automatically set to g5.12xlarge.
[INFO] INSTANCES = g5.12xlarge

An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id sagemaker-hyperpod does not exist
[ERROR] failed to retrieve VPC ID
create_config.sh: line 56: return: can only `return' from a function or sourced script

An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id sagemaker-hyperpod does not exist
[ERROR] failed to retrieve SUBNET ID
create_config.sh: line 71: return: can only `return' from a function or sourced script

An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id sagemaker-hyperpod does not exist
[ERROR] failed to retrieve Public SUBNET ID
create_config.sh: line 86: return: can only `return' from a function or sourced script

An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id sagemaker-hyperpod does not exist
[ERROR] failed to retrieve FSX ID
create_config.sh: line 101: return: can only `return' from a function or sourced script

An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id sagemaker-hyperpod does not exist
[ERROR] failed to retrieve FSX Mountname
create_config.sh: line 116: return: can only `return' from a function or sourced script

An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id sagemaker-hyperpod does not exist
[ERROR] failed to retrieve FSX Security Group
create_config.sh: line 131: return: can only `return' from a function or sourced script

An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id sagemaker-hyperpod does not exist
[ERROR] failed to retrieve Role ARN
create_config.sh: line 146: return: can only `return' from a function or sourced script
[ERROR] failed to retrieve Role NAME
create_config.sh: line 157: return: can only `return' from a function or sourced script

An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id sagemaker-hyperpod does not exist
[ERROR] failed to retrieve Bucket Name
create_config.sh: line 172: return: can only `return' from a function or sourced script```

I am using cloudshell, and IAM role has been setup properly. Not sure what's wrong.

**Comment by mhuguesaws** [comment]
Did you deploy the VPC stack https://catalog.workshops.aws/sagemaker-hyperpod/en-US/00-setup/02-own-account?
