### ISSUE TITLE
Remove aws pytorch references

### ISSUE THREAD

**Issue by sean-smith** [aws-samples/awsome-distributed-training#446]
Tracking issue for all the instances of `--strict-channel-priority --override-channels -c https://aws-ml-conda.s3.us-west-2.amazonaws.com` like:

https://github.com/aws-samples/awsome-distributed-training/blob/ee14c5371562233c710962a866a0355660318573/3.test_cases/16.pytorch-cpu-ddp/slurm/0.create-conda-env.sh#L13

**Comment by mhuguesaws** [comment]
Duplicate #444
