### ISSUE TITLE
Data loaders best practices guide

### ISSUE THREAD

**Issue by perifaws** [aws-samples/awsome-distributed-training#52]
Create a best practices guide to data loaders

**Comment by perifaws** [comment]
@awsankur  https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-s3-connector-pytorch/

**Comment by KeitaW** [comment]
https://aws.amazon.com/jp/blogs/aws/new-amazon-s3-express-one-zone-high-performance-storage-class/
