### ISSUE TITLE
How to specify Placement Group Id in cluster config?

### ISSUE THREAD

**Issue by awsankur** [aws-samples/awsome-distributed-training#54]
The default way is to not enable Placement Group when using a ODCR to create a cluster. But when the ODCR has a Placement Group already specified, how do we specify the Placement Group ID in the cluster creation config?

**Comment by awsankur** [comment]
If there is a Placement Group attached to the ODCR.....we can specify the PlacementGroup as below and when creating the cluster add `--suppress-validators "type:ComputeResourceLaunchTemplateValidator"`

```
PlacementGroup:
          Name: p5-pg-cr
```

**Comment by awsankur** [comment]
pcluster create-cluster --cluster-configuration p5-config-pg-no-ami.yaml --cluster-name awsankur-p5-pcluster --region us-west-2 --suppress-validators "type:InstanceTypeBaseAMICompatibleValidator" --suppress-validators "type:ComputeResourceLaunchTemplateValidator" --rollback-on-failure "false"

**Comment by sean-smith** [comment]
Placement group should be set to false (disabled) when using a ODCR:
```yaml
PlacementGroup:
  Enabled: false
```

**Comment by awsankur** [comment]
Not if a PG is enabled in the ODCR

**Comment by verdimrc** [comment]
hi, so to conclude, what's the recommended way?

**Comment by mhuguesaws** [comment]
Add the placement group in the configuration file of ParallelCluster.
