### ISSUE TITLE
Images for 5.sagemaker-hyperpod are missing

### ISSUE THREAD

**Issue by KeitaW** [aws-samples/awsome-distributed-training#60]
cf. https://github.com/aws-samples/awsome-distributed-training/tree/main/1.architectures/5.sagemaker-hyperpod

https://github.com/aws-samples/awsome-distributed-training/blob/main/0.docs/vpc-template.png

and 

https://github.com/aws-samples/awsome-distributed-training/blob/main/0.docs/fsx-lustre-template.png

are missing.

**Comment by johnbensnyder** [comment]
Added missing images in [this PR](https://github.com/aws-samples/awsome-distributed-training/pull/62).

**Comment by KeitaW** [comment]
Addressed by the PR. Thanks @johnbensnyder
