### ISSUE TITLE
NCCL_PROTO

### ISSUE THREAD

**Issue by sean-smith** [aws-samples/awsome-distributed-training#86]
Should we be setting this:

https://github.com/aws-samples/awsome-distributed-training/blob/57c7d4767831f267e9b7a437461fe9ecad4a9f59/2.ami_and_containers/1.amazon_machine_image/roles/nvidia_nccl/tasks/main.yml#L39

**Comment by verdimrc** [comment]
It depends. Needed for aws-ofi-nccl<=1.5 ([ref](https://github.com/aws/aws-ofi-nccl/blob/master/doc/efa-env-var.md))

**Comment by mhuguesaws** [comment]
default NCCL parameters are sufficient.
