### ISSUE TITLE
xformers version on the MPT docker file has to be pinned.

### ISSUE THREAD

**Issue by aruncs2005** [aws-samples/awsome-distributed-training#88]
Recently we noticed that the example - https://github.com/aws-samples/awsome-distributed-training/blob/main/3.test_cases/3.MPT/0.llm-foundry.Dockerfile causes the training to fail and we had to pin the xformers version to 0.0.22 to mitigate this. Please update the repo to pin the version.

**Comment by KeitaW** [comment]
Thanks for reporting the issue!
